version: '3.9'

services:
  php_apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "88:80"
    volumes:
      - ./tltleave:/var/www/html/tltleave
    networks:
      - tltleave_network

  mysql:
    image: mysql:8.0.36
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Onepiece87*
      MYSQL_DATABASE: tltleavedb
      MYSQL_USER: tlt_user
      MYSQL_PASSWORD: tlt_password
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - tltleave_network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - tltleave_network

  composer:
    image: composer:2.7.4
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/tltleave
    command: ["composer", "install"]
    networks:
      - tltleave_network

volumes:
  mysql:

networks:
  tltleave_network:

